# Generated by Django 3.0.3 on 2022-04-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220418_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='contentState',
            field=models.TextField(blank=True),
        ),
    ]
