# Generated by Django 3.0.3 on 2022-04-20 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_task_contentstate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='contentState',
        ),
    ]
